services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env.local
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  my-db: